version: '3'

services:
  postgres:
    container_name: 'kilid'
    image: 'postgres'
    environment:
      POSTGRES_USER: 'pg'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - '../postgres:/data/postgres'
    ports:
      - '5432:5432'
    networks:
      - 'postgres'
    restart: 'on-failure'

networks:
  postgres:
    driver: bridge
